version: '3.9'
services: 
    jupyter:
        build: 
            context: Jupyterlab/.
        privileged: true
        user: root
        ports: 
            - 80:8888
        environment:
            JUPYTER_ENABLE_LAB: "yes"
            GRANT_SUDO: "yes"
        volumes: 
            - ./Jupyterlab/notebooks:/home/jovyan/work
            - ./Solara/app:/home/jovyan/solara-app
        command: 
            "start-notebook.sh --NotebookApp.token=''"  
    ros2:
        image: ros:iron-ros-core  
        privileged: true
        command: 
            "tail -f /dev/null"   
    solara:
        build: 
            context: Solara/.  
        ports:
            - 8080:80
        volumes:
            - ./Solara/app:/home/solara-app
      